name = "LinearAlgebraMPI"
uuid = "5bdd2be4-ae34-42ef-8b36-f4c85d48f377"
version = "0.1.6"
authors = ["S. Loisel"]

[deps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
Blake3Hash = "8f478455-a32d-4928-b0e4-72b19a7d5574"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
MUMPS = "55d2b088-9f4e-11e9-26c0-150b02ea6a46"
Metal = "dde4c033-4e86-420c-a63e-0dd931031962"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[extensions]
LinearAlgebraMPIMetalExt = "Metal"

[compat]
Adapt = "4"
Blake3Hash = "0.3"
KernelAbstractions = "0.9"
MPI = "0.20"
MUMPS = "1.5"
Metal = "1.9.1"
PrecompileTools = "1"
StaticArrays = "1"
julia = "1.10"

[extras]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Metal = "dde4c033-4e86-420c-a63e-0dd931031962"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Random", "Test", "Metal"]
